security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
          memory:
            users:
              test:
                 password: test
                 roles: 'ROLE_USER'
              admin:
                 password: admin
                 roles: 'ROLE_ADMIN'
    role_hierarchy:
        ROLE_WORKER:       ROLE_USER
        ROLE_SUPERVISOR:       ROLE_WORKER
        ROLE_ADMIN:       [ROLE_WORKER,ROLE_USER]
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH] #top user can switch to other users
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        main:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
